###################                                                                                                                                                                                                                                                          
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = $terminal -e ranger
$menu = ~/.config/rofi/launchers/type-1/launcher.sh
$browser = brave
$daw = reaper
$music = spotify
$screenshot = grim "Pictures/Grim/$(date +'%s_grimss.png')"
