
##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

#windowrule = match:float True, center on

windowrule = match:class brave-browser, workspace 2 silent
windowrule = match:class brave-hjlhbeffadgkonmpnblkfmhckmocohah-Default, opacity 1.0 1.0
windowrule = match:class spotify, workspace 5 silent
windowrule = match:class REAPER, match:float False, workspace 3
windowrule = match:class REAPER, match:float True, workspace 3 silent
windowrule = match:class Godot, workspace 3
windowrule = match:class codium, workspace 3
windowrule = match:class org.kde.kdenlive, workspace 3
windowrule = match:class Audacity, workspace 3
windowrule = match:class gimp, workspace 3
windowrule = match:class steam, workspace 4
windowrule = match:class CurseForge, workspace 4
windowrule = match:class heroic, workspace 4
windowrule = match:class discord, workspace 4
windowrule = match:class kitty, workspace 1
windowrule = match:class Element, workspace 4
windowrule = match:content 3, opacity 1.0 1.0
windowrule = match:content 3, workspace 4
windowrule = match:class Minecraft.*, workspace 4
windowrule = match:class jetbrains-idea, workspace 3
windowrule = match:class jetbrains-pycharm, workspace 3
windowrule = match:class jetbrains-rustrover, workspace 3
windowrule = match:class jetbrains-rubymine, workspace 3
