background {
	monitor =
	path = ~/Pictures/system-pics/wallpaper-dark-pixelized.png
}

input-field {
	monitor =
	size = 300, 50
	outline_thickness = 3
	dots_size = 0.33
	dots_spacing = 0.15
	dots_center = true
	dots_rounding = -1
	outer_color = rgb(f9d8e9)
	inner_color = rgb(f38ac3)
	font_color = rgb(f9d8e9)
	fade_on_empty = true
	fade_timeout = 3000 # milliseconds
	placeholder_text = <i>Type 'Er In...</i>
	hide_input = false
	rounding = -1
	check_color = rgb(204, 136, 34)
	fail_color = rgb(204, 34, 34)
	fail_transition = 50 # ms
	capslock_color = -1
	numlock_color = -1
	bothlock_color = -1
	invert_numlock = false
	swap_font_color = false
	position = 0, -20
	halign = center
	valign = center
}

label {
	monitor =
	text = cmd[update:1000] echo "$TIME"
	color = rgba(f9d8e9ff)
	font_size = 55
	font_family = JetBrainsMono Regular
	position = -100, 40
	halign = right
	valign = bottom
	shadow_passes = 5
	shadow_size = 10
}

label {
	monitor =
	text = "Actually, it's GNU/Linux" -God
	color = rgba(f9d8e9ff)
	font_size = 20
	font_family = JetBrainsMono Regular
	position = -100, 160
	halign = right
	valign = bottom
	shadow_passes = 5
	shadow_size = 10
}
